export type FormulaCategory = 'algebra' | 'geometry' | 'informatics';

export interface Formula {
  id: string;
  category: FormulaCategory;
  name: string;
  latex: string;
  description: string;
  keywords: string[];
}

export const formulasData: Formula[] = [
  // АЛГЕБРА
  {
    id: 'alg-1',
    category: 'algebra',
    name: 'Қысқаша көбейту формулалары (Квадрат)',
    latex: '(a \\pm b)^2 = a^2 \\pm 2ab + b^2',
    description: 'Екі өрнектің қосындысының немесе айырмасының квадраты.',
    keywords: ['квадрат', 'қысқаша', 'көбейту', 'алгебра'],
  },
  {
    id: 'alg-2',
    category: 'algebra',
    name: 'Квадраттар айырмасы',
    latex: 'a^2 - b^2 = (a - b)(a + b)',
    description: 'Екі өрнектің квадраттарының айырмасы.',
    keywords: ['квадрат', 'айырма', 'алгебра'],
  },
  {
    id: 'alg-3',
    category: 'algebra',
    name: 'Куб формулалары (Қосынды)',
    latex: '(a + b)^3 = a^3 + 3a^2b + 3ab^2 + b^3',
    description: 'Екі өрнектің қосындысының кубы.',
    keywords: ['куб', 'қысқаша', 'көбейту', 'алгебра'],
  },
  {
    id: 'alg-4',
    category: 'algebra',
    name: 'Кубтар айырмасы',
    latex: 'a^3 - b^3 = (a - b)(a^2 + ab + b^2)',
    description: 'Екі өрнектің кубтарының айырмасы.',
    keywords: ['куб', 'айырма', 'алгебра'],
  },
  {
    id: 'alg-5',
    category: 'algebra',
    name: 'Квадрат теңдеу (Дискриминант)',
    latex: 'D = b^2 - 4ac, \\quad x_{1,2} = \\frac{-b \\pm \\sqrt{D}}{2a}',
    description: 'ax² + bx + c = 0 квадрат теңдеуінің түбірлерін табу.',
    keywords: ['квадрат', 'теңдеу', 'дискриминант', 'түбір'],
  },
  {
    id: 'alg-6',
    category: 'algebra',
    name: 'Виет теоремасы',
    latex: 'x_1 + x_2 = -\\frac{b}{a}, \\quad x_1 x_2 = \\frac{c}{a}',
    description: 'Келтірілген квадрат теңдеудің (x² + px + q = 0) түбірлері мен коэффициенттері арасындағы байланыс.',
    keywords: ['виет', 'теорема', 'түбір'],
  },
  {
    id: 'alg-7',
    category: 'algebra',
    name: 'Арифметикалық прогрессия (n-ші мүше)',
    latex: 'a_n = a_1 + (n - 1)d',
    description: 'Арифметикалық прогрессияның n-ші мүшесін табу.',
    keywords: ['арифметикалық', 'прогрессия', 'тізбек'],
  },
  {
    id: 'alg-8',
    category: 'algebra',
    name: 'Арифметикалық прогрессия қосындысы',
    latex: 'S_n = \\frac{2a_1 + (n - 1)d}{2} \\cdot n = \\frac{a_1 + a_n}{2} \\cdot n',
    description: 'Алғашқы n мүшесінің қосындысы.',
    keywords: ['арифметикалық', 'прогрессия', 'қосынды'],
  },
  {
    id: 'alg-9',
    category: 'algebra',
    name: 'Геометриялық прогрессия (n-ші мүше)',
    latex: 'b_n = b_1 \\cdot q^{n - 1}',
    description: 'Геометриялық прогрессияның n-ші мүшесін табу.',
    keywords: ['геометриялық', 'прогрессия', 'тізбек'],
  },
  {
    id: 'alg-10',
    category: 'algebra',
    name: 'Дәреже қасиеттері (Көбейту)',
    latex: 'a^m \\cdot a^n = a^{m+n}',
    description: 'Негіздері бірдей дәрежелерді көбейткенде көрсеткіштер қосылады.',
    keywords: ['дәреже', 'көбейту', 'қасиет'],
  },
  {
    id: 'alg-11',
    category: 'algebra',
    name: 'Логарифмнің негізгі тепе-теңдігі',
    latex: 'a^{\\log_a b} = b',
    description: 'Егер a > 0, a ≠ 1 және b > 0 болса.',
    keywords: ['логарифм', 'тепе-теңдік', 'қасиет'],
  },
  {
    id: 'alg-13',
    category: 'algebra',
    name: 'Синус (тригонометрия)',
    latex: '\\sin(A) = \\frac{\\text{Қарама-қарсы}}{\\text{Гипотенуза}}',
    description: 'Тік бұрышты үшбұрыштың синусы.',
    keywords: ['синус', 'тригонометрия', 'бұрыш', 'син'],
  },
  {
    id: 'alg-14',
    category: 'algebra',
    name: 'Косинус (тригонометрия)',
    latex: '\\cos(A) = \\frac{\\text{Іргелес}}{\\text{Гипотенуза}}',
    description: 'Тік бұрышты үшбұрыштың косинусы.',
    keywords: ['косинус', 'тригонометрия', 'бұрыш', 'кос'],
  },
  {
    id: 'alg-15',
    category: 'algebra',
    name: 'Тангенс (тригонометрия)',
    latex: '\\tan(A) = \\frac{\\sin(A)}{\\cos(A)} = \\frac{\\text{Қарама-қарсы}}{\\text{Іргелес}}',
    description: 'Тік бұрышты үшбұрыштың тангенсі.',
    keywords: ['тангенс', 'тригонометрия', 'бұрыш', 'тан'],
  },
  {
    id: 'alg-16',
    category: 'algebra',
    name: 'Котангенс (тригонометрия)',
    latex: '\\cot(A) = \\frac{1}{\\tan(A)} = \\frac{\\cos(A)}{\\sin(A)}',
    description: 'Тік бұрышты үшбұрыштың котангенсі.',
    keywords: ['котангенс', 'тригонометрия', 'бұрыш'],
  },
  {
    id: 'alg-17',
    category: 'algebra',
    name: 'Негізгі тригонометриялық тепе-теңдік',
    latex: '\\sin^2(\\alpha) + \\cos^2(\\alpha) = 1',
    description: 'Синус пен косинус квадраттарының қосындысы.',
    keywords: ['тригонометрия', 'тепе-теңдік', 'син', 'кос'],
  },
  {
    id: 'alg-18',
    category: 'algebra',
    name: 'Қосындының синусы',
    latex: '\\sin(\\alpha + \\beta) = \\sin\\alpha \\cos\\beta + \\cos\\alpha \\sin\\beta',
    description: 'Екі бұрыштың қосындысының синусы.',
    keywords: ['синус', 'қосынды', 'тригонометрия'],
  },
  {
    id: 'alg-19',
    category: 'algebra',
    name: 'Қосындының косинусы',
    latex: '\\cos(\\alpha + \\beta) = \\cos\\alpha \\cos\\beta - \\sin\\alpha \\sin\\beta',
    description: 'Екі бұрыштың қосындысының косинусы.',
    keywords: ['косинус', 'қосынды', 'тригонометрия'],
  },
  {
    id: 'alg-20',
    category: 'algebra',
    name: 'Айырманың синусы',
    latex: '\\sin(\\alpha - \\beta) = \\sin\\alpha \\cos\\beta - \\cos\\alpha \\sin\\beta',
    description: 'Екі бұрыштың айырмасының синусы.',
    keywords: ['синус', 'айырма', 'тригонометрия'],
  },
  {
    id: 'alg-21',
    category: 'algebra',
    name: 'Айырманың косинусы',
    latex: '\\cos(\\alpha - \\beta) = \\cos\\alpha \\cos\\beta + \\sin\\alpha \\sin\\beta',
    description: 'Екі бұрыштың айырмасының косинусы.',
    keywords: ['косинус', 'айырма', 'тригонометрия'],
  },
  {
    id: 'alg-22',
    category: 'algebra',
    name: 'Екі бұрыштың синусы',
    latex: '\\sin(2\\alpha) = 2\\sin\\alpha \\cos\\alpha',
    description: 'Қос бұрыштың синусы.',
    keywords: ['синус', 'қос', 'екі', 'тригонометрия'],
  },
  {
    id: 'alg-23',
    category: 'algebra',
    name: 'Екі бұрыштың косинусы',
    latex: '\\cos(2\\alpha) = \\cos^2\\alpha - \\sin^2\\alpha = 2\\cos^2\\alpha - 1 = 1 - 2\\sin^2\\alpha',
    description: 'Қос бұрыштың косинусы (үш түрі).',
    keywords: ['косинус', 'қос', 'екі', 'тригонометрия'],
  },
  {
    id: 'alg-24',
    category: 'algebra',
    name: 'Синусты косинусқа түрлендіру',
    latex: '\\sin\\alpha = \\cos(90° - \\alpha), \\quad \\sin\\alpha = \\cos(\\frac{\\pi}{2} - \\alpha)',
    description: 'Синус пен косинус арасындағы қатынас.',
    keywords: ['синус', 'косинус', 'түрлендіру', 'тригонометрия'],
  },
  {
    id: 'alg-25',
    category: 'algebra',
    name: 'Синустар қосындысы',
    latex: '\\sin\\alpha + \\sin\\beta = 2\\sin\\frac{\\alpha + \\beta}{2}\\cos\\frac{\\alpha - \\beta}{2}',
    description: 'Екі синустың қосындысын көбейтіндіге түрлендіру.',
    keywords: ['синус', 'қосынды', 'түрлендіру', 'тригонометрия'],
  },
  {
    id: 'alg-26',
    category: 'algebra',
    name: 'Синустар айырмасы',
    latex: '\\sin\\alpha - \\sin\\beta = 2\\cos\\frac{\\alpha + \\beta}{2}\\sin\\frac{\\alpha - \\beta}{2}',
    description: 'Екі синустың айырмасын көбейтіндіге түрлендіру.',
    keywords: ['синус', 'айырма', 'түрлендіру', 'тригонометрия'],
  },
  {
    id: 'alg-27',
    category: 'algebra',
    name: 'Косинустар қосындысы',
    latex: '\\cos\\alpha + \\cos\\beta = 2\\cos\\frac{\\alpha + \\beta}{2}\\cos\\frac{\\alpha - \\beta}{2}',
    description: 'Екі косинустың қосындысын көбейтіндіге түрлендіру.',
    keywords: ['косинус', 'қосынды', 'түрлендіру', 'тригонометрия'],
  },
  {
    id: 'alg-28',
    category: 'algebra',
    name: 'Косинустар айырмасы',
    latex: '\\cos\\alpha - \\cos\\beta = -2\\sin\\frac{\\alpha + \\beta}{2}\\sin\\frac{\\alpha - \\beta}{2}',
    description: 'Екі косинустың айырмасын көбейтіндіге түрлендіру.',
    keywords: ['косинус', 'айырма', 'түрлендіру', 'тригонометрия'],
  },
  {
    id: 'alg-29',
    category: 'algebra',
    name: 'Өрнектеу бірлігі тригонометрияда',
    latex: '\\sin(\\frac{\\pi}{6}) = \\frac{1}{2}, \\quad \\sin(\\frac{\\pi}{4}) = \\frac{\\sqrt{2}}{2}, \\quad \\sin(\\frac{\\pi}{3}) = \\frac{\\sqrt{3}}{2}',
    description: 'Ерекше бұрыштардың синустарының мәндері.',
    keywords: ['синус', 'мәндер', 'бұрыш', 'тригонометрия', 'таблица'],
  },
  {
    id: 'alg-31',
    category: 'algebra',
    name: 'Системаларды шешу (Қосу әдісі)',
    latex: '\\begin{cases} a_1x + b_1y = c_1 \\\\ a_2x + b_2y = c_2 \\end{cases}',
    description: 'Екі теңдеуден тұратын жүйені шешу.',
    keywords: ['система', 'теңдеу', 'қосу', 'әдіс'],
  },
  {
    id: 'alg-32',
    category: 'algebra',
    name: 'Системаларды шешу (Ауыстыру әдісі)',
    latex: 'x = \\frac{c_1 - b_1y}{a_1}, \\quad y = \\frac{c_2 - a_2x}{b_2}',
    description: 'Бір айнымалыны тауып, екіншісіне қою.',
    keywords: ['система', 'теңдеу', 'ауыстыру', 'әдіс'],
  },
  {
    id: 'alg-33',
    category: 'algebra',
    name: 'Квадрат теңдеулер жүйесі',
    latex: '\\begin{cases} x^2 + y^2 = a \\\\ x + y = b \\end{cases}',
    description: 'Квадраттар қосындысы мен қосындысы берілген.',
    keywords: ['система', 'квадрат', 'теңдеу'],
  },
  {
    id: 'alg-34',
    category: 'algebra',
    name: 'Куб теңдеу (Кардано формуласы)',
    latex: 'x = \\sqrt[3]{-\\frac{q}{2} + \\sqrt{(\\frac{q}{2})^2 + (\\frac{p}{3})^3}} + \\sqrt[3]{-\\frac{q}{2} - \\sqrt{(\\frac{q}{2})^2 + (\\frac{p}{3})^3}}',
    description: 'x³ + px + q = 0 куб теңдеуінің түбірлерін табу.',
    keywords: ['куб', 'теңдеу', 'кардано', 'формула'],
  },
  {
    id: 'alg-35',
    category: 'algebra',
    name: 'Квадрат теңсіздік',
    latex: 'ax^2 + bx + c > 0, \\quad D = b^2 - 4ac',
    description: 'Квадрат теңсіздікті шешу.',
    keywords: ['теңсіздік', 'квадрат', 'дискриминант'],
  },
  {
    id: 'alg-36',
    category: 'algebra',
    name: 'Рационал теңсіздік',
    latex: '\\frac{f(x)}{g(x)} > 0',
    description: 'Рационалдық теңсіздікті шешу.',
    keywords: ['теңсіздік', 'рационал', 'бөлшек'],
  },
  {
    id: 'alg-37',
    category: 'algebra',
    name: 'Модуль теңсіздігі',
    latex: '|x| < a \\quad \\Rightarrow \\quad -a < x < a',
    description: 'Модульді теңсіздікті шешу.',
    keywords: ['теңсіздік', 'модуль', 'абсолют'],
  },
  {
    id: 'alg-38',
    category: 'algebra',
    name: 'Комбинациялар саны',
    latex: 'C_n^k = \\frac{n!}{k!(n-k)!}',
    description: 'n элементтен k элементтің комбинациясы.',
    keywords: ['комбинаторика', 'комбинация', 'факториал'],
  },
  {
    id: 'alg-40',
    category: 'algebra',
    name: 'Орналастырулар саны',
    latex: 'P_n^k = \\frac{n!}{(n-k)!}',
    description: 'n элементтен k элементтің орналастыруы.',
    keywords: ['комбинаторика', 'орналастыру', 'факториал'],
  },
  {
    id: 'alg-41',
    category: 'algebra',
    name: 'Вариациялар саны',
    latex: 'A_n^k = n^k',
    description: 'Қайталанумен n элементтен k элементтің вариациясы.',
    keywords: ['комбинаторика', 'вариация', 'қайталану'],
  },
  {
    id: 'alg-42',
    category: 'algebra',
    name: 'Вероятность',
    latex: 'P(A) = \\frac{m}{n}',
    description: 'Оқиға А-ның ықтималдығы.',
    keywords: ['вероятность', 'ықтималдық', 'оқиға'],
  },
  {
    id: 'alg-43',
    category: 'algebra',
    name: 'Екі оқиғаның қосындысының ықтималдығы',
    latex: 'P(A \\cup B) = P(A) + P(B) - P(A \\cap B)',
    description: 'Екі оқиғаның бірі болу ықтималдығы.',
    keywords: ['вероятность', 'қосынды', 'оқиға'],
  },
  {
    id: 'alg-44',
    category: 'algebra',
    name: 'Шартты ықтималдық',
    latex: 'P(A|B) = \\frac{P(A \\cap B)}{P(B)}',
    description: 'B оқиғасы болған жағдайда A оқиғасының ықтималдығы.',
    keywords: ['вероятность', 'шартты', 'оқиға'],
  },
  {
    id: 'alg-45',
    category: 'algebra',
    name: 'Комплекс сандар',
    latex: 'z = a + bi, \\quad |z| = \\sqrt{a^2 + b^2}',
    description: 'Комплекс санның модулі.',
    keywords: ['комплекс', 'сан', 'модуль'],
  },
  {
    id: 'alg-46',
    category: 'algebra',
    name: 'Комплекс сандардың қосындысы',
    latex: '(a + bi) + (c + di) = (a + c) + (b + d)i',
    description: 'Комплекс сандарды қосу.',
    keywords: ['комплекс', 'сан', 'қосынды'],
  },
  {
    id: 'alg-47',
    category: 'algebra',
    name: 'Комплекс сандардың көбейтіндісі',
    latex: '(a + bi)(c + di) = ac + adi + bci + bdi^2 = (ac - bd) + (ad + bc)i',
    description: 'Комплекс сандарды көбейту.',
    keywords: ['комплекс', 'сан', 'көбейтінді'],
  },
  {
    id: 'alg-48',
    category: 'algebra',
    name: 'Векторлардың қосындысы',
    latex: '\\vec{a} + \\vec{b} = (a_x + b_x, a_y + b_y, a_z + b_z)',
    description: 'Векторларды қосу.',
    keywords: ['вектор', 'қосынды', 'координата'],
  },
  {
    id: 'alg-53',
    category: 'algebra',
    name: 'Векторлардың скаляр көбейтіндісі',
    latex: '\\vec{a} \\cdot \\vec{b} = |\\vec{a}| \\cdot |\\vec{b}| \\cos\\alpha = a_x b_x + a_y b_y + a_z b_z',
    description: 'Векторлардың скаляр көбейтіндісі.',
    keywords: ['вектор', 'скаляр', 'көбейтінді'],
  },
  {
    id: 'alg-54',
    category: 'algebra',
    name: 'Производнаяның негізгі ережелері',
    latex: '(u \\pm v)^\\prime = u^\\prime \\pm v^\\prime, \\quad (cu)^\\prime = c u^\\prime',
    description: 'Қосынды мен көбейтіндінің туындысы.',
    keywords: ['производная', 'туынды', 'ережелер'],
  },
  {
    id: 'alg-56',
    category: 'algebra',
    name: 'Дәреженің туындысы',
    latex: '(x^n)^\\prime = n x^{n-1}',
    description: 'Дәрежелі функцияның туындысы.',
    keywords: ['производная', 'туынды', 'дәреже'],
  },
  {
    id: 'alg-57',
    category: 'algebra',
    name: 'Экспонентаның туындысы',
    latex: '(e^x)^\\prime = e^x, \\quad (a^x)^\\prime = a^x \\ln a',
    description: 'Экспоненталық функциялардың туындысы.',
    keywords: ['производная', 'туынды', 'экспонента'],
  },
  {
    id: 'alg-58',
    category: 'algebra',
    name: 'Логарифмнің туындысы',
    latex: '(\\ln x)^\\prime = \\frac{1}{x}, \\quad (\\log_a x)^\\prime = \\frac{1}{x \\ln a}',
    description: 'Логарифмдік функциялардың туындысы.',
    keywords: ['производная', 'туынды', 'логарифм'],
  },
  {
    id: 'alg-59',
    category: 'algebra',
    name: 'Тригонометриялық функциялардың туындысы',
    latex: '(\\sin x)^\\prime = \\cos x, \\quad (\\cos x)^\\prime = -\\sin x',
    description: 'Синус пен косинустың туындысы.',
    keywords: ['производная', 'туынды', 'тригонометрия'],
  },
  {
    id: 'alg-60',
    category: 'algebra',
    name: 'Интегралдың негізгі ережелері',
    latex: '\\int (u \\pm v) dx = \\int u dx \\pm \\int v dx, \\quad \\int c f(x) dx = c \\int f(x) dx',
    description: 'Интегралдың сызықтық қасиеттері.',
    keywords: ['интеграл', 'ережелер', 'сызықтық'],
  },
  {
    id: 'alg-61',
    category: 'algebra',
    name: 'Дәрежені интегралдау',
    latex: '\\int x^n dx = \\frac{x^{n+1}}{n+1} + C, \\quad n \\neq -1',
    description: 'Дәрежелі функцияны интегралдау.',
    keywords: ['интеграл', 'дәреже', 'константа'],
  },
  {
    id: 'alg-62',
    category: 'algebra',
    name: 'Экспонентаны интегралдау',
    latex: '\\int e^x dx = e^x + C, \\quad \\int a^x dx = \\frac{a^x}{\\ln a} + C',
    description: 'Экспоненталық функцияларды интегралдау.',
    keywords: ['интеграл', 'экспонента', 'константа'],
  },
  {
    id: 'alg-63',
    category: 'algebra',
    name: 'Тригонометриялық интегралдар',
    latex: '\\int \\sin x dx = -\\cos x + C, \\quad \\int \\cos x dx = \\sin x + C',
    description: 'Синус пен косинусты интегралдау.',
    keywords: ['интеграл', 'тригонометрия', 'константа'],
  },
  {
    id: 'alg-64',
    category: 'algebra',
    name: 'Анықталған интеграл',
    latex: '\\int_a^b f(x) dx = F(b) - F(a)',
    description: 'Ньютон-Лейбниц формуласы.',
    keywords: ['интеграл', 'анықталған', 'ньютон', 'лейбниц'],
  },
  {
    id: 'alg-65',
    category: 'algebra',
    name: 'Интегралдың геометриялық мағынасы',
    latex: '\\int_a^b f(x) dx = S',
    description: 'Анықталған интегралдың аудан ретіндегі мағынасы.',
    keywords: ['интеграл', 'геометриялық', 'аудан'],
  },

  // ГЕОМЕТРИЯ
  {
    id: 'geo-1',
    category: 'geometry',
    name: 'Пифагор теоремасы',
    latex: 'c^2 = a^2 + b^2',
    description: 'Тік бұрышты үшбұрыштың гипотенузасының квадраты катеттерінің квадраттарының қосындысына тең.',
    keywords: ['пифагор', 'үшбұрыш', 'гипотенуза', 'катет'],
  },
  {
    id: 'geo-2',
    category: 'geometry',
    name: 'Синустар теоремасы',
    latex: '\\frac{a}{\\sin A} = \\frac{b}{\\sin B} = \\frac{c}{\\sin C} = 2R',
    description: 'Үшбұрыштың қабырғалары мен қарама-қарсы бұрыштарының синустарының қатынасы.',
    keywords: ['синус', 'теорема', 'үшбұрыш', 'радиус'],
  },
  {
    id: 'geo-3',
    category: 'geometry',
    name: 'Косинустар теоремасы',
    latex: 'c^2 = a^2 + b^2 - 2ab\\cos C',
    description: 'Кез келген үшбұрыштың қабырғалары мен бұрыштары арасындағы қатынас.',
    keywords: ['косинус', 'теорема', 'үшбұрыш'],
  },
  {
    id: 'geo-4',
    category: 'geometry',
    name: 'Тік төртбұрыштың ауданы',
    latex: 'S = a \\cdot b',
    description: 'Тік төртбұрыштың ауданы оның ені мен ұзындығының көбейтіндісіне тең.',
    keywords: ['аудан', 'төртбұрыш'],
  },
  {
    id: 'geo-5',
    category: 'geometry',
    name: 'Үшбұрыштың ауданы (Табаны мен биіктігі)',
    latex: 'S = \\frac{1}{2} a \\cdot h',
    description: 'Үшбұрыштың ауданы табаны мен оған түсірілген биіктіктің көбейтіндісінің жартысына тең.',
    keywords: ['аудан', 'үшбұрыш', 'биіктік'],
  },
  {
    id: 'geo-6',
    category: 'geometry',
    name: 'Үшбұрыштың ауданы (Герон формуласы)',
    latex: 'S = \\sqrt{p(p-a)(p-b)(p-c)}, \\quad p = \\frac{a+b+c}{2}',
    description: 'Үш қабырғасы арқылы үшбұрыштың ауданын табу.',
    keywords: ['аудан', 'үшбұрыш', 'герон', 'периметр'],
  },
  {
    id: 'geo-7',
    category: 'geometry',
    name: 'Үшбұрыштың ауданы (Екі қабырға мен бұрыш)',
    latex: 'S = \\frac{1}{2} ab\\sin C',
    description: 'Екі қабырға мен оларының арасындағы бұрыш арқылы ауданы табу.',
    keywords: ['аудан', 'үшбұрыш', 'синус'],
  },
  {
    id: 'geo-8',
    category: 'geometry',
    name: 'Параллелограмдың ауданы',
    latex: 'S = a \\cdot h = ab\\sin\\alpha',
    description: 'Табаны мен биіктігі немесе екі қабырға мен бұрыш арқылы ауданы табу.',
    keywords: ['аудан', 'параллелограмм'],
  },
  {
    id: 'geo-9',
    category: 'geometry',
    name: 'Ромбтың ауданы',
    latex: 'S = \\frac{d_1 \\cdot d_2}{2}',
    description: 'Екі диагоналінің арқылы ромбтың ауданы табу.',
    keywords: ['аудан', 'ромб', 'диагональ'],
  },
  {
    id: 'geo-10',
    category: 'geometry',
    name: 'Трапецияның ауданы',
    latex: 'S = \\frac{a + b}{2} \\cdot h',
    description: 'Екі табаны мен биіктігі арқылы трапецияның ауданы табу.',
    keywords: ['аудан', 'трапеция', 'биіктік'],
  },
  {
    id: 'geo-11',
    category: 'geometry',
    name: 'Шеңбердің ұзындығы',
    latex: 'C = 2\\pi R = \\pi d',
    description: 'Радиусы R немесе диаметрі d болатын шеңбердің ұзындығы.',
    keywords: ['шеңбер', 'ұзындық', 'радиус', 'диаметр'],
  },
  {
    id: 'geo-12',
    category: 'geometry',
    name: 'Дөңгелектің ауданы',
    latex: 'S = \\pi R^2',
    description: 'Радиусы R болатын дөңгелектің ауданы.',
    keywords: ['дөңгелек', 'аудан', 'радиус'],
  },
  {
    id: 'geo-13',
    category: 'geometry',
    name: 'Сектордың ауданы',
    latex: 'S = \\frac{\\alpha}{360°} \\cdot \\pi R^2 = \\frac{\\pi R^2 \\alpha}{360°}',
    description: 'Радиусы R және орталық бұрышы α болатын сектордың ауданы.',
    keywords: ['сектор', 'аудан', 'шеңбер', 'бұрыш'],
  },
  {
    id: 'geo-14',
    category: 'geometry',
    name: 'Сегменттің ауданы',
    latex: 'S = R^2(\\frac{\\pi\\alpha}{180°} - \\sin\\alpha)',
    description: 'Радиусы R және орталық бұрышы α болатын сегменттің ауданы.',
    keywords: ['сегмент', 'аудан', 'шеңбер', 'хорда'],
  },
  {
    id: 'geo-15',
    category: 'geometry',
    name: 'Цилиндр көлемі',
    latex: 'V = \\pi R^2 h',
    description: 'Цилиндрдің табанының ауданы мен биіктігінің көбейтіндісі.',
    keywords: ['көлем', 'цилиндр', 'биіктік'],
  },
  {
    id: 'geo-16',
    category: 'geometry',
    name: 'Цилиндрдің толық беті',
    latex: 'S = 2\\pi R^2 + 2\\pi R h = 2\\pi R(R + h)',
    description: 'Цилиндрдің екі табаны мен бүйіні.',
    keywords: ['бет', 'цилиндр', 'аудан'],
  },
  {
    id: 'geo-17',
    category: 'geometry',
    name: 'Конус көлемі',
    latex: 'V = \\frac{1}{3}\\pi R^2 h',
    description: 'Конустың табанының ауданы мен биіктігі.',
    keywords: ['көлем', 'конус', 'биіктік'],
  },
  {
    id: 'geo-18',
    category: 'geometry',
    name: 'Конусдың бүйіні',
    latex: 'S_{\\text{бүйін}} = \\pi R l',
    description: 'Генератрисасы l болатын конусдың бүйіні.',
    keywords: ['бет', 'конус', 'генератрис'],
  },
  {
    id: 'geo-19',
    category: 'geometry',
    name: 'Конусдың толық беті',
    latex: 'S = \\pi R^2 + \\pi R l = \\pi R(R + l)',
    description: 'Табаны мен бүйіні.',
    keywords: ['бет', 'конус', 'аудан'],
  },
  {
    id: 'geo-20',
    category: 'geometry',
    name: 'Пирамида көлемі',
    latex: 'V = \\frac{1}{3}S_{\\text{т}} \\cdot h',
    description: 'Табанының ауданы мен биіктігі арқылы пирамида көлемі.',
    keywords: ['көлем', 'пирамида', 'биіктік'],
  },
  {
    id: 'geo-21',
    category: 'geometry',
    name: 'Кубоидтың көлемі',
    latex: 'V = a \\cdot b \\cdot c',
    description: 'Қабырғалары a, b, c болатын кубоидтың көлемі.',
    keywords: ['көлем', 'кубоид', 'ұзындық'],
  },
  {
    id: 'geo-22',
    category: 'geometry',
    name: 'Кубтың көлемі',
    latex: 'V = a^3',
    description: 'Қабырғасы a болатын кубтың көлемі.',
    keywords: ['көлем', 'куб', 'қабырға'],
  },
  {
    id: 'geo-23',
    category: 'geometry',
    name: 'Шардың көлемі',
    latex: 'V = \\frac{4}{3}\\pi R^3',
    description: 'Радиусы R болатын шардың көлемі.',
    keywords: ['көлем', 'шар', 'радиус'],
  },
  {
    id: 'geo-24',
    category: 'geometry',
    name: 'Сфераның ауданы',
    latex: 'S = 4\\pi R^2',
    description: 'Радиусы R болатын сфераның бет ауданы.',
    keywords: ['аудан', 'сфера', 'шар'],
  },
  {
    id: 'geo-25',
    category: 'geometry',
    name: 'Үшбұрыштың периметрі',
    latex: 'P = a + b + c',
    description: 'Үшбұрыштың барлық қабырғаларының қосындысы.',
    keywords: ['периметр', 'үшбұрыш'],
  },
  {
    id: 'geo-26',
    category: 'geometry',
    name: 'Үшбұрыштың ішінде сызылған шеңбердің радиусы',
    latex: 'r = \\frac{S}{p}, \\quad p = \\frac{a+b+c}{2}',
    description: 'Ауданы S және жарты-периметрі p болатын үшбұрыштың ішінде сызылған шеңбер.',
    keywords: ['радиус', 'үшбұрыш', 'шеңбер', 'инсцентр'],
  },
  {
    id: 'geo-27',
    category: 'geometry',
    name: 'Үшбұрыштың айналасында сызылған шеңбердің радиусы',
    latex: 'R = \\frac{abc}{4S}',
    description: 'Қабырғалары a, b, c және ауданы S болатын үшбұрыш.',
    keywords: ['радиус', 'үшбұрыш', 'шеңбер', 'циркумсцентр'],
  },
  {
    id: 'geo-28',
    category: 'geometry',
    name: 'Призма көлемі',
    latex: 'V = S_{\\text{т}} \\cdot h',
    description: 'Табанының ауданы мен биіктігі арқылы призма көлемі.',
    keywords: ['көлем', 'призма', 'биіктік'],
  },

  // ИНФОРМАТИКА
  {
    id: 'inf-1',
    category: 'informatics',
    name: 'Ақпарат көлемі (Хартли формуласы)',
    latex: 'N = 2^i',
    description: 'Мұндағы N — ықтимал оқиғалар (алфавит қуаты), i — ақпарат саны (бит).',
    keywords: ['ақпарат', 'көлем', 'хартли', 'бит', 'алфавит'],
  },
  {
    id: 'inf-2',
    category: 'informatics',
    name: 'Мәтіндік хабарлама көлемі',
    latex: 'I = K \\cdot i',
    description: 'I — хабардың көлемі, K — таңбалар саны, i — бір таңбаның салмағы (бит).',
    keywords: ['мәтін', 'көлем', 'таңба', 'бит'],
  },
  {
    id: 'inf-3',
    category: 'informatics',
    name: 'Суреттің ақпараттық көлемі',
    latex: 'V = W \\cdot H \\cdot i, \\quad K = 2^i',
    description: 'W, H — пиксельмен ені мен биіктігі, i — түс тереңдігі (бит), K — түстер саны.',
    keywords: ['сурет', 'көлем', 'пиксель', 'түс', 'палитра'],
  },
  {
    id: 'inf-4',
    category: 'informatics',
    name: 'Дыбыстың ақпараттық көлемі',
    latex: 'V = f \\cdot i \\cdot t \\cdot c',
    description: 'f - дискреттеу жиілігі, i - тереңдігі, t - уақыт, c - каналдар саны (моно=1, стерео=2).',
    keywords: ['дыбыс', 'көлем', 'жиілік', 'стерео', 'аудио'],
  },
  {
    id: 'inf-5',
    category: 'informatics',
    name: 'Файлды тасымалдау уақыты',
    latex: 't = \\frac{V}{v}',
    description: 'V - файл көлемі, v - жылдамдық (бит/с), t - уақыт (с).',
    keywords: ['тасымалдау', 'жылдамдық', 'уақыт', 'файл', 'желі'],
  },
  {
    id: 'inf-6',
    category: 'informatics',
    name: 'Екілік санау жүйесінен ондыққа',
    latex: '1011_2 = 1\\cdot2^3 + 0\\cdot2^2 + 1\\cdot2^1 + 1\\cdot2^0 = 11_{10}',
    description: 'Кез келген санау жүйесінен ондыққа ауыстыру ережесі.',
    keywords: ['санау', 'екілік', 'ондық', 'жүйе', 'аударма'],
  },
  {
    id: 'inf-7',
    category: 'informatics',
    name: 'Логикалық конъюнкция (ЖӘНЕ)',
    latex: 'A \\land B \\quad (A \\,\\&\\, B)',
    description: 'Тек екі пікір де ақиқат (1) болғанда ғана нәтиже ақиқат.',
    keywords: ['логика', 'конъюнкция', 'және', 'анд', 'and'],
  },
  {
    id: 'inf-8',
    category: 'informatics',
    name: 'Логикалық дизъюнкция (НЕМЕСЕ)',
    latex: 'A \\lor B \\quad (A \\mid B)',
    description: 'Кем дегенде бір пікір ақиқат (1) болса, нәтиже ақиқат.',
    keywords: ['логика', 'дизъюнкция', 'немесе', 'or'],
  },
  {
    id: 'inf-9',
    category: 'informatics',
    name: 'Логикалық терістеу (ЕМЕС)',
    latex: '\\neg A',
    description: 'Пікірдің ақиқаттығын керісінше өзгертеді.',
    keywords: ['логика', 'терістеу', 'емес', 'not'],
  },
];

